service: visitor-lambda

frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs22.x
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    memorySize: 512
    timeout: 30
    environment:
        NODE_ENV: ${self:provider.stage}
        REDIS_HOST: ${env:REDIS_HOST, 'localhost'}
        REDIS_PORT: ${env:REDIS_PORT, '6379'}
        REDIS_PASSWORD: ${env:REDIS_PASSWORD, ''}

    # IAM role for Lambda execution
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                  Resource:
                      - 'arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*:*:*'

functions:
    api:
        handler: dist/index.handler
        events:
            - httpApi:
                  path: /{proxy+}
                  method: ANY
            - httpApi:
                  path: /
                  method: ANY

package:
    patterns:
        - 'dist/index.js'
        - 'dist-api/**'
        - '!src/**'
        - '!node_modules/**'
        - '!test-local.js'
        - '!*.md'
        - '!tsconfig.json'

plugins:
    - serverless-offline

custom:
    serverless-offline:
        httpPort: 3000
        host: 0.0.0.0
